// THIS FILE IS AUTO-GENERATED BY scripts/extract-themes.js
export interface ThemeInfo {
  id: string;
  name: string;
  background: string;
  cardBg: string;
  text: string;
  border: string;
  accent: string;
}

export const THEMES_LIST: ThemeInfo[] = [
  {
    id: "system",
    name: "System Theme",
    background: "linear-gradient(135deg, #f8fafc 50%, #070a13 50%)",
    cardBg: "linear-gradient(135deg, #ffffff 50%, #0b0f19 50%)",
    text: "#3b82f6",
    border: "rgba(15, 23, 42, 0.08)",
    accent: "#3b82f6"
  },
  {
    id: "light",
    name: "Light Theme",
    background: "#f8fafc",
    cardBg: "#ffffff",
    text: "#0f172a",
    border: "rgba(15, 23, 42, 0.08)",
    accent: "#3b82f6"
  },
  {
    id: "dark",
    name: "Dark Theme",
    background: "#070a13",
    cardBg: "#0b0f19",
    text: "#f8fafc",
    border: "rgba(255, 255, 255, 0.08)",
    accent: "#38bdf8"
  },
  {
    id: "angular",
    name: "Angular Red",
    background: "#0c0812",
    cardBg: "#140d1f",
    text: "#ffffff",
    border: "rgba(226, 28, 52, 0.15)",
    accent: "#e21c34"
  },
  {
    id: "nordic-light",
    name: "Nordic Light",
    background: "#f1f5f9",
    cardBg: "#ffffff",
    text: "#1e293b",
    border: "rgba(30, 41, 59, 0.08)",
    accent: "#0284c7"
  },
  {
    id: "peach-blossom",
    name: "Peach Blossom",
    background: "#fffaf5",
    cardBg: "#ffffff",
    text: "#2d1a12",
    border: "rgba(45, 26, 18, 0.08)",
    accent: "#f43f5e"
  },
  {
    id: "neo-mint",
    name: "Neo Mint",
    background: "#f0fdf4",
    cardBg: "#ffffff",
    text: "#064e3b",
    border: "rgba(6, 78, 59, 0.12)",
    accent: "#0d9488"
  },
  {
    id: "cyberpunk-dark",
    name: "Cyberpunk Dark",
    background: "#0f051d",
    cardBg: "#1a0b2e",
    text: "#f8fafc",
    border: "rgba(255, 0, 127, 0.25)",
    accent: "#ff007f"
  },
  {
    id: "emerald-abyss",
    name: "Emerald Abyss",
    background: "#040d0e",
    cardBg: "#0b1c1e",
    text: "#e6f4f1",
    border: "rgba(16, 185, 129, 0.15)",
    accent: "#10b981"
  },
  {
    id: "brutalist-light",
    name: "Brutalist Light",
    background: "#f4f4f5",
    cardBg: "#ffffff",
    text: "#000000",
    border: "#000000",
    accent: "#facc15"
  },
  {
    id: "brutalist-dark",
    name: "Brutalist Dark",
    background: "#000000",
    cardBg: "#18181b",
    text: "#ffffff",
    border: "#ffffff",
    accent: "#a855f7"
  },
  {
    id: "aero-light",
    name: "Aero Light",
    background: "#f0f9ff",
    cardBg: "rgba(255, 255, 255, 0.7)",
    text: "#0c4a6e",
    border: "rgba(56, 189, 248, 0.25)",
    accent: "#22c55e"
  },
  {
    id: "aero-dark",
    name: "Aero Dark",
    background: "#082f49",
    cardBg: "rgba(15, 23, 42, 0.6)",
    text: "#e0f2fe",
    border: "rgba(14, 165, 233, 0.3)",
    accent: "#0ea5e9"
  },
  {
    id: "pixel-light",
    name: "Pixel Light",
    background: "#c0c0c0",
    cardBg: "#ffffff",
    text: "#000000",
    border: "#000000",
    accent: "#000080"
  },
  {
    id: "pixel-dark",
    name: "Pixel Dark",
    background: "#000000",
    cardBg: "#051005",
    text: "#39ff14",
    border: "#39ff14",
    accent: "#39ff14"
  }
];
