import fs from 'node:fs';
import path from 'node:path';

const THEMES_CSS_PATH = path.join(process.cwd(), 'src/themes.css');
const OUTPUT_PATH = path.join(
  process.cwd(),
  'src/app/modules/catalog/presentation/views/themes-view/theme-data.ts'
);

function capitalizeAndFormat(id) {
  if (id === 'light') return 'Light Theme';
  if (id === 'dark') return 'Dark Theme';
  if (id === 'angular') return 'Angular Red';
  
  return id
    .split('-')
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join(' ');
}

function parseThemes() {
  const cssContent = fs.readFileSync(THEMES_CSS_PATH, 'utf-8');

  // Simple regex to match blocks like `.classname { ... }` or `:root, .classname { ... }`
  const blockRegex = /([^{]+)\{([^}]+)\}/g;
  
  const themes = [];
  
  // Keep the 'system' theme as a hardcoded static entry first
  themes.push({
    id: 'system',
    name: 'System Theme',
    background: 'linear-gradient(135deg, #f8fafc 50%, #070a13 50%)',
    cardBg: 'linear-gradient(135deg, #ffffff 50%, #0b0f19 50%)',
    text: '#3b82f6',
    border: 'rgba(15, 23, 42, 0.08)',
    accent: '#3b82f6',
  });

  let match;
  while ((match = blockRegex.exec(cssContent)) !== null) {
    const selector = match[1].trim();
    const rulesStr = match[2];
    
    // Extract the actual id. Might be `:root, .light` or just `.dark`
    let id = '';
    const classMatch = selector.match(/\.([a-zA-Z0-9_-]+)/);
    if (classMatch) {
      id = classMatch[1];
    } else {
      continue; // Skip if no class found
    }

    const rules = {};
    const propRegex = /--([^:]+):\s*([^;]+);/g;
    let propMatch;
    
    while ((propMatch = propRegex.exec(rulesStr)) !== null) {
      rules[propMatch[1].trim()] = propMatch[2].trim();
    }

    if (Object.keys(rules).length > 0) {
      themes.push({
        id: id,
        name: capitalizeAndFormat(id),
        background: rules['background'] || '',
        cardBg: rules['card-bg'] || '',
        text: rules['text'] || '',
        border: rules['border'] || '',
        accent: rules['accent'] || '',
      });
    }
  }

  const outputCode = `// THIS FILE IS AUTO-GENERATED BY scripts/extract-themes.js
export interface ThemeInfo {
  id: string;
  name: string;
  background: string;
  cardBg: string;
  text: string;
  border: string;
  accent: string;
}

export const THEMES_LIST: ThemeInfo[] = ${JSON.stringify(themes, null, 2).replace(/"([^"]+)":/g, '$1:')};
`;

  fs.writeFileSync(OUTPUT_PATH, outputCode, 'utf-8');
  console.log(`Successfully mapped themes from themes.css to ${OUTPUT_PATH}`);
}

parseThemes();
